apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    app: microservices
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: flask
  - port: 8001
    protocol: TCP
    name: prometheus_stats
  selector:
    app: mywebapp
    env: prod
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mywebapp
    env: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        app: mywebapp
        env: prod
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp:prod
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "16Mi" # mebibytes
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "16Mi"
            cpu: "100m"
        ports:
          - containerPort: 5000
          - containerPort: 8001
